[build]
  command = ""
  publish = "."

[context.production]
  command = ""
  publish = "."

[context.deploy-preview]
  command = ""
  publish = "."

[context.branch-deploy]
  command = ""
  publish = "."
